version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
     - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kaigishiwebsite_db
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
     - .:/code
    ports:
     - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - db

volumes:
  postgres-data: