# Generated by Django 4.2.7 on 2024-02-08 01:36

from django.db import migrations, models
import django.db.models.deletion
import kakomon.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField(default=kakomon.functions.default_exam_id)),
                ('date', models.DateField(verbose_name='定期')),
                ('exam_type', models.CharField(choices=[('writing', '筆記'), ('speaking', '口述')], max_length=8, verbose_name='筆記・口述')),
                ('grade', models.CharField(choices=[('grade1', '1級'), ('grade2', '2級'), ('grade3', '3級')], max_length=6, verbose_name='級名')),
                ('navigation_or_mechanism', models.CharField(choices=[('navigation', '航海'), ('mechanism', '機関')], max_length=10, verbose_name='航海・機関')),
            ],
            options={
                'ordering': ['-exam_id'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('navigation', '航海'), ('operation', '運用'), ('law', '法規'), ('english', '英語'), ('mechanism1', '機関1'), ('mechanism2', '機関2'), ('mechanism3', '機関3'), ('working', '執務一般')], max_length=10, verbose_name='科目')),
                ('name_order', models.IntegerField(choices=[(1, 'navigation'), (2, 'operation'), (3, 'law'), (4, 'english'), (5, 'mechanism1'), (6, 'mechanism2'), (7, 'mechanism3'), (8, 'working')], verbose_name='科目順序')),
                ('file_path', models.FileField(blank=True, null=True, upload_to=kakomon.functions.get_file_path, verbose_name='PDF')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='kakomon.exam', verbose_name='試験')),
            ],
            options={
                'ordering': ['-exam__exam_id', 'name_order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='問題ID')),
                ('daimon', models.PositiveSmallIntegerField(verbose_name='大問')),
                ('shomon', models.IntegerField(blank=True, choices=[(1, '一'), (2, '二'), (3, '三'), (4, '四'), (5, '五')], null=True, verbose_name='小問')),
                ('edamon', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='枝問')),
                ('description_flex', models.BooleanField(default=False, verbose_name='問題説明を大問横に表示')),
                ('description', models.TextField(blank=True, null=True, verbose_name='問題説明')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to=kakomon.functions.get_image_upload_path, verbose_name='問題画像')),
                ('question', models.TextField(verbose_name='問題')),
                ('answer_no_indent', models.BooleanField(default=False, verbose_name='解答インデント無')),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to=kakomon.functions.get_image_upload_path, verbose_name='解答画像')),
                ('answer', models.TextField(verbose_name='解答')),
                ('similar_questions', models.ManyToManyField(blank=True, to='kakomon.question', verbose_name='類似問題')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakomon.subject', verbose_name='科目')),
            ],
            options={
                'ordering': ['subject', 'daimon', 'shomon', 'edamon'],
            },
        ),
    ]
