# Generated by Django 4.2.7 on 2023-12-21 02:09

from django.db import migrations, models
import django.db.models.deletion
import kakomon.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField(default=kakomon.models.Exam.get_exam_id)),
                ('date', models.DateField(verbose_name='定期')),
                ('exam_type', models.CharField(choices=[('writing', '筆記'), ('speaking', '口述')], max_length=8, verbose_name='筆記・口述')),
                ('grade', models.CharField(choices=[('grade1', '1級'), ('grade2', '2級'), ('grade3', '3級')], max_length=6, verbose_name='級名')),
                ('navigation_or_mechanism', models.CharField(choices=[('navigation', '航海'), ('mechanism', '機関')], max_length=10, verbose_name='航海・機関')),
            ],
            options={
                'ordering': ['exam_id'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('navigation', '航海'), ('operation', '運用'), ('law', '法規'), ('english', '英語'), ('mechanism1', '機関1'), ('mechanism2', '機関2'), ('mechanism3', '機関3'), ('working', '執務一般')], max_length=10, verbose_name='科目')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='kakomon.exam', verbose_name='試験')),
            ],
            options={
                'ordering': ['exam__exam_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daimon', models.PositiveSmallIntegerField()),
                ('shomon', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('edamon', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to=kakomon.models.Question.get_image_upload_path)),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to=kakomon.models.Question.get_image_upload_path)),
                ('question_description', models.TextField(blank=True, null=True)),
                ('question', models.TextField()),
                ('answer_no_indent', models.BooleanField(default=False)),
                ('answer', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakomon.subject', verbose_name='科目')),
            ],
            options={
                'ordering': ['subject', 'daimon', 'shomon', 'edamon'],
            },
        ),
    ]
