# Generated by Django 4.2.7 on 2023-12-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakomon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['exam__exam_id', 'name_order']},
        ),
        migrations.AddField(
            model_name='subject',
            name='name_order',
            field=models.IntegerField(choices=[(1, 'navigation'), (2, 'operation'), (3, 'law'), (4, 'english'), (5, 'mechanism1'), (6, 'mechanism2'), (7, 'mechanism3'), (8, 'working')], default=1),
            preserve_default=False,
        ),
    ]
