# Generated by Django 4.2.7 on 2024-03-28 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakomon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='カテゴリー')),
            ],
            options={
                'verbose_name': 'カテゴリー',
                'verbose_name_plural': '4.カテゴリー',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='タグ')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': '5.タグ',
            },
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-date', '-navigation_or_mechanism'], 'verbose_name': '試験', 'verbose_name_plural': '1.試験'},
        ),
        migrations.AlterModelOptions(
            name='similarquestion',
            options={'verbose_name': '類似問題', 'verbose_name_plural': '6.類似問題'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-exam__exam_id', 'name_order'], 'verbose_name': '科目', 'verbose_name_plural': '2.科目'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer_image_position',
            new_name='answer_image_position_right_or_under',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_image_position',
        ),
        migrations.AddField(
            model_name='question',
            name='question_image_position_description_or_question',
            field=models.CharField(blank=True, choices=[('description', '説明'), ('question', '問題')], default=None, max_length=11, null=True, verbose_name='問題画像配置1'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image_position_right_or_under',
            field=models.CharField(blank=True, choices=[('right', '右'), ('under', '下')], default=None, max_length=5, null=True, verbose_name='問題画像配置2'),
        ),
        migrations.AlterField(
            model_name='similarquestion',
            name='similar_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar', to='kakomon.question', verbose_name='類似問題'),
        ),
        migrations.AlterField(
            model_name='similarquestion',
            name='source_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='kakomon.question', verbose_name='元問題'),
        ),
        migrations.AddField(
            model_name='similarquestion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakomon.category'),
        ),
        migrations.AddField(
            model_name='similarquestion',
            name='tags',
            field=models.ManyToManyField(blank=True, to='kakomon.tag', verbose_name='タグ'),
        ),
    ]
