# Generated by Django 4.2.7 on 2024-05-04 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakomon', '0002_alter_exam_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='navigation_or_mechanism', #例：変更したい変数名
            new_name='navigation_or_engineering' #例：変更後の変数名
        )
    ]
