# Generated by Django 4.2.7 on 2023-12-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakomon', '0002_alter_subject_options_subject_name_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name_order',
            field=models.IntegerField(choices=[(1, 'navigation'), (2, 'operation'), (3, 'law'), (4, 'english'), (5, 'mechanism1'), (6, 'mechanism2'), (7, 'mechanism3'), (8, 'working')], verbose_name='科目順序'),
        ),
    ]
