# Generated by Django 4.2.7 on 2024-04-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakomon', '0002_alter_exam_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='navigation_or_engineering',
            field=models.CharField(choices=[('navigation', '航海'), ('engineering', '機関')], max_length=11, verbose_name='航海・機関'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('navigation', '航海'), ('operation', '運用'), ('law', '法規'), ('english', '英語'), ('engineering1', '機関1'), ('engineering2', '機関2'), ('engineering3', '機関3'), ('working', '執務一般')], max_length=12, verbose_name='科目'),
        ),
    ]
