# Generated by Django 4.2.7 on 2024-05-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakomon', '0003_auto_20240504_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-date', '-navigation_or_engineering', 'grade'], 'verbose_name': '試験', 'verbose_name_plural': '1.試験'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-subject__exam__date', '-subject__exam__navigation_or_engineering', 'subject__exam__grade', 'subject__name_order', 'daimon', 'shomon', 'edamon'], 'verbose_name': '問題', 'verbose_name_plural': '3.問題'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-exam__date', '-exam__navigation_or_engineering', 'exam__grade', 'name_order'], 'verbose_name': '科目', 'verbose_name_plural': '2.科目'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='navigation_or_engineering',
            field=models.CharField(choices=[('navigation', '航海'), ('engineering', '機関')], max_length=11, verbose_name='航海・機関'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('navigation', '航海'), ('operation', '運用'), ('law', '法規'), ('english', '英語'), ('engineering1', '機関1'), ('engineering2', '機関2'), ('engineering3', '機関3'), ('working', '執務一般')], max_length=12, verbose_name='科目'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name_order',
            field=models.IntegerField(choices=[(1, 'navigation'), (2, 'operation'), (3, 'law'), (4, 'english'), (5, 'engineering1'), (6, 'engineering2'), (7, 'engineering3'), (8, 'working')], verbose_name='科目順序'),
        ),
    ]
