# Generated by Django 4.2.7 on 2023-12-28 09:29

from django.db import migrations, models
import kakomon.models


class Migration(migrations.Migration):

    dependencies = [
        ('kakomon', '0004_alter_exam_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to=kakomon.models.Subject.get_file_path, verbose_name='PDF'),
        ),
    ]
