# Generated by Django 4.2.7 on 2023-12-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakomon', '0005_subject_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='similar_questions',
            field=models.ManyToManyField(blank=True, to='kakomon.question'),
        ),
    ]
