# Generated by Django 4.2.7 on 2023-12-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakomon', '0006_question_similar_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='similar_questions',
            field=models.ManyToManyField(blank=True, to='kakomon.question', verbose_name='類似問題'),
        ),
    ]
