# Generated by Django 4.2.7 on 2024-01-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakomon', '0007_alter_question_similar_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='question',
            name='description_flex',
            field=models.BooleanField(default=False, verbose_name='問題説明を大問横に表示'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_no_indent',
            field=models.BooleanField(default=False, verbose_name='解答インデント無'),
        ),
    ]
